import styles from './grid.module.scss';

export const Grid = () => (
  <table className={styles.table}>
    <tbody>
      <tr className={styles.row}>
        <td className={styles.cell}>0</td>
        <td className={styles.cell}>1</td>
        <td className={styles.cell}>2</td>
        <td className={styles.cell}>3</td>
        <td className={styles.cell}>4</td>
        <td className={styles.cell}>5</td>
        <td className={styles.cell}>6</td>
        <td className={styles.cell}>7</td>
        <td className={styles.cell}>8</td>
        <td className={styles.cell}>9</td>
        <td className={styles.cell}>10</td>
        <td className={styles.cell}>11</td>
        <td className={styles.cell}>12</td>
        <td className={styles.cell}>13</td>
        <td className={styles.cell}>14</td>
        <td className={styles.cell}>15</td>
        <td className={styles.cell}>16</td>
        <td className={styles.cell}>17</td>
        <td className={styles.cell}>18</td>
        <td className={styles.cell}>19</td>
        <td className={styles.cell}>20</td>
        <td className={styles.cell}>21</td>
        <td className={styles.cell}>22</td>
        <td className={styles.cell}>23</td>
        <td className={styles.cell}>24</td>
        <td className={styles.cell}>25</td>
        <td className={styles.cell}>26</td>
        <td className={styles.cell}>28</td>
        <td className={styles.cell}>29</td>
        <td className={styles.cell}>30</td>
        <td className={styles.cell}>31</td>
        <td className={styles.cell}>32</td>
      </tr>
      <tr className={styles.row}>
        <td className={styles.cell}>1</td>
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
      </tr>
      <tr className={styles.row}>
        <td className={styles.cell}>2</td>
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
      </tr>
      <tr className={styles.row}>
        <td className={styles.cell}>3</td>
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
      </tr>
      <tr className={styles.row}>
        <td className={styles.cell}>4</td>
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
      </tr>
      <tr className={styles.row}>
        <td className={styles.cell}>5</td>
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
      </tr>
      <tr className={styles.row}>
        <td className={styles.cell}>6</td>
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
      </tr>
      <tr className={styles.row}>
        <td className={styles.cell}>7</td>
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
      </tr>
      <tr className={styles.row}>
        <td className={styles.cell}>8</td>
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
      </tr>
      <tr className={styles.row}>
        <td className={styles.cell}>9</td>
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
      </tr>
      <tr className={styles.row}>
        <td className={styles.cell}>10</td>
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
      </tr>
      <tr className={styles.row}>
        <td className={styles.cell}>11</td>
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
      </tr>
      <tr className={styles.row}>
        <td className={styles.cell}>12</td>
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
      </tr>
      <tr className={styles.row}>
        <td className={styles.cell}>13</td>
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
      </tr>
      <tr className={styles.row}>
        <td className={styles.cell}>14</td>
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
      </tr>
      <tr className={styles.row}>
        <td className={styles.cell}>15</td>
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
      </tr>
      <tr className={styles.row}>
        <td className={styles.cell}>16</td>
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
      </tr>
      <tr className={styles.row}>
        <td className={styles.cell}>17</td>
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
      </tr>
      <tr className={styles.row}>
        <td className={styles.cell}>18</td>
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
      </tr>
      <tr className={styles.row}>
        <td className={styles.cell}>19</td>
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
      </tr>
      <tr className={styles.row}>
        <td className={styles.cell}>20</td>
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
      </tr>
      <tr className={styles.row}>
        <td className={styles.cell}>21</td>
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
      </tr>
      <tr className={styles.row}>
        <td className={styles.cell}>22</td>
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
      </tr>
      <tr className={styles.row}>
        <td className={styles.cell}>23</td>
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
      </tr>
      <tr className={styles.row}>
        <td className={styles.cell}>24</td>
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
      </tr>
      <tr className={styles.row}>
        <td className={styles.cell}>25</td>
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
      </tr>
      <tr className={styles.row}>
        <td className={styles.cell}>26</td>
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
      </tr>
      <tr className={styles.row}>
        <td className={styles.cell}>27</td>
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
        <td className={styles.cell} />
      </tr>
    </tbody>
  </table>
);
