import { useEffect, useState } from 'react';
import Head from 'next/head';
import { useSelector, useDispatch } from 'react-redux';

import BoardCheckers from '../../checkers/components/Home/BoardCheckers';
import { Board } from '../../checkers/model/Board';
import { Player } from '../../checkers/model/Player';
import { Colors } from '../../checkers/model/Colors';
import { Figure } from '../../checkers/model/figures/Figure';
import { RootState } from '../../store';
import { setShow } from '../../checkers/store/checkersReducer';
import { players, player } from '../../checkers/components/Lobbi/PlayersForOnlinePlay';

export default function Play() {
  const dispatch = useDispatch();
  const { isPlayWithBoot, idForPlayersOnline, color, bid } = useSelector(
    (state: RootState) => state.checkers,
  );

  const setPlayer = () => {
    const blackAndWhitePlayers = [];
    let colorForMyUser;
    let bids;
    if (!isPlayWithBoot) {
      const selectedPlayer = players.find((p) => p.id === idForPlayersOnline);
      console.log(selectedPlayer);
      console.log(players);
      console.log(idForPlayersOnline);

      blackAndWhitePlayers.push(
        new Player(
          selectedPlayer?.id,

          selectedPlayer?.name,
          selectedPlayer?.playConditional.bid,

          selectedPlayer?.playConditional.colorCheckers,
        ),
      );

      if (selectedPlayer?.playConditional.colorCheckers === color) {
        if (selectedPlayer?.playConditional.colorCheckers === 'black') {
          colorForMyUser = Colors.WHITE;
        } else {
          colorForMyUser = Colors.BLACK;
        }
      } else {
        colorForMyUser = color;
      }
      if (selectedPlayer?.playConditional.bid !== bid) {
        bids = selectedPlayer?.playConditional.bid;
      }
      blackAndWhitePlayers.push(new Player(player.id, player.name, bids, colorForMyUser));
      console.log(blackAndWhitePlayers);

      return blackAndWhitePlayers;
    }
    const WHITE_BOT_NAME = 'Белого Игрока';
    const BLACK_BOT_NAME = 'Черного Игрока';
    blackAndWhitePlayers.push(new Player(null, WHITE_BOT_NAME, null, Colors.WHITE));
    blackAndWhitePlayers.push(new Player(null, BLACK_BOT_NAME, null, Colors.BLACK));
    return blackAndWhitePlayers;
  };
  const [board, setBoard] = useState(new Board());

  const [whitePlayer] = useState(setPlayer().find((el) => el.color === Colors.WHITE));
  const [blackPlayer] = useState(setPlayer().find((el) => el.color === Colors.BLACK));
  const [currentPlayer, setCurrentPlayer] = useState<Player | null>(whitePlayer);
  const [currentFigure, setCurrentFigure] = useState<Figure | null>(null);

  const restart = () => {
    const newBoard = new Board();
    newBoard.initBoard();
    newBoard.addFigures();
    setBoard(newBoard);
  };
  useEffect(() => {
    restart();
    dispatch(setShow(true));
    setCurrentPlayer(whitePlayer);
  }, []);

  const switchPlayerColor = (currentFigure: Figure | null, currentPlayer: Player | null) => {
    if (currentPlayer?.color === Colors.WHITE) {
      return blackPlayer;
    }
    return whitePlayer;
  };

  const swapPlayer = (ok: string) => {
    if (ok === 'one') {
      setCurrentPlayer(switchPlayerColor(currentFigure, currentPlayer));
    } else if (ok === 'two') {
      setCurrentPlayer(blackPlayer);
    } else if (ok === 'three') {
      setCurrentPlayer(whitePlayer);
    } else if (ok === 'four') {
      setCurrentPlayer(null);
    }
  };

  const swapFigure = (figure: Figure | null) => {
    if (figure) {
      setCurrentFigure(figure);
      setCurrentPlayer(null);
    } else {
      setCurrentFigure(null);
    }
  };

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="app">
        <BoardCheckers
          board={board}
          setBoard={setBoard}
          currentPlayer={currentPlayer}
          currentFigure={currentFigure}
          swapPlayer={swapPlayer}
          swapFigure={swapFigure}
          restart={restart}
        />
      </main>
    </div>
  );
}
