import { useEffect, useState } from 'react';
import Head from 'next/head';
import { useSelector } from 'react-redux';

import BoardCheckers from '../../checkers/components/Home/BoardCheckers';
import { Board } from '../../checkers/model/Board';
import { Player } from '../../checkers/model/Player';
import { Colors } from '../../checkers/model/Colors';
import { Figure } from '../../checkers/model/figures/Figure';
import { RootState } from '../../store';
import { players } from '../../checkers/components/Lobbi/PlayersForOnlinePlay';

export default function Play() {
  const { isPlayWithBoot } = useSelector((state: RootState) => state.checkers);
  let whiteP;
  let blackP;
  const setPlayer = () => {
    if (isPlayWithBoot) {
      const findWhite = players.find((p) => p.playConditional.colorCheckers === 'white');
      whiteP = new Player(
        findWhite.id,
        findWhite.name,
        findWhite.playConditional.bid,
        Colors.WHITE,
      );
      const findBlack = players.find((p) => p.playConditional.colorCheckers === 'black');
      blackP = new Player(
        findBlack.id,
        findBlack.name,
        findBlack.playConditional.bid,
        Colors.BLACK,
      );
    } else {
      whiteP = new Player(null, null, null, Colors.WHITE);
      blackP = new Player(null, null, null, Colors.BLACK);
    }
  };
  setPlayer();
  const [board, setBoard] = useState(new Board());
  const [show, setShow] = useState(false);
  const [whitePlayer] = useState(whiteP);
  const [blackPlayer] = useState(blackP);
  const [currentPlayer, setCurrentPlayer] = useState<Player | null>(null);
  const [currentFigure, setCurrentFigure] = useState<Figure | null>(null);

  const restart = () => {
    const newBoard = new Board();
    newBoard.initBoard();
    newBoard.addFigures();
    setBoard(newBoard);
  };
  useEffect(() => {
    restart();
    setShow(true);
    setCurrentPlayer(whitePlayer);
  }, []);

  const switchPlayerColor = (currentFigure: Figure | null, currentPlayer: Player | null) => {
    if (currentPlayer?.color === Colors.WHITE) {
      return blackPlayer;
    }
    return whitePlayer;
  };

  const swapPlayer = (ok: string) => {
    if (ok === 'one') {
      setCurrentPlayer(switchPlayerColor(currentFigure, currentPlayer));
    } else if (ok === 'two') {
      setCurrentPlayer(blackPlayer);
    } else if (ok === 'three') {
      setCurrentPlayer(whitePlayer);
    } else if (ok === 'four') {
      setCurrentPlayer(null);
    }
  };

  const swapFigure = (figure: Figure | null) => {
    if (figure) {
      setCurrentFigure(figure);
      setCurrentPlayer(null);
    } else {
      setCurrentFigure(null);
    }
  };

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="app">
        <BoardCheckers
          board={board}
          setBoard={setBoard}
          currentPlayer={currentPlayer}
          currentFigure={currentFigure}
          swapPlayer={swapPlayer}
          swapFigure={swapFigure}
          restart={restart}
          show={show}
          setShow={setShow}
        />
      </main>
    </div>
  );
}
